# Generated by Django 3.1.2 on 2020-10-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprogress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='Python'),
            preserve_default=False,
        ),
    ]
