# Generated by Django 3.1.2 on 2020-10-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprogress', '0002_auto_20201029_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=False),
        ),
    ]
