# Generated by Django 3.1.2 on 2020-10-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprogress', '0002_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledcourse',
            name='name',
            field=models.CharField(default=True, max_length=300, null=True),
        ),
    ]
