# Generated by Django 3.1.2 on 2020-10-29 13:37

from django.db import migrations, models
import userprogress.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprogress', '0003_auto_20201029_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledcourse',
            name='slug',
            field=models.SlugField(default=userprogress.models.Course),
        ),
    ]
