# Generated by Django 3.1.2 on 2020-10-23 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprogress', '0003_auto_20201023_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledcourse',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ucourse', to=settings.AUTH_USER_MODEL),
        ),
    ]
