# Generated by Django 3.1.2 on 2020-10-19 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprogress', '0003_enrolledcourse_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledcourse',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
