# Generated by Django 3.1.2 on 2020-10-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprogress', '0006_auto_20201020_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolledcourse',
            name='course',
        ),
        migrations.AddField(
            model_name='enrolledcourse',
            name='course',
            field=models.ManyToManyField(related_name='course', to='userprogress.Course'),
        ),
    ]
