# Generated by Django 3.1.2 on 2020-10-20 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprogress', '0009_auto_20201020_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolledcourse',
            name='course',
        ),
    ]
