# Generated by Django 3.1.2 on 2020-10-20 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprogress', '0010_remove_enrolledcourse_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledcourse',
            name='course',
            field=models.ForeignKey(default='C', on_delete=django.db.models.deletion.CASCADE, related_name='course', to='userprogress.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrolledcourse',
            name='name',
            field=models.ForeignKey(default='Carter', on_delete=django.db.models.deletion.CASCADE, related_name='name', to='auth.user'),
            preserve_default=False,
        ),
    ]
