# Generated by Django 3.1.2 on 2020-10-20 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprogress', '0012_auto_20201020_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledcourse',
            name='course',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='userprogress.course'),
        ),
    ]
