# Generated by Django 3.1.2 on 2020-10-20 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprogress', '0013_auto_20201020_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolledcourse',
            name='course',
        ),
    ]
