# Generated by Django 3.1.2 on 2020-10-17 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolledcourse',
            name='course',
        ),
        migrations.DeleteModel(
            name='CompletedCourse',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='EnrolledCourse',
        ),
    ]
