# Generated by Django 3.1.2 on 2020-10-17 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_cpp_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpp',
            name='slug',
        ),
    ]
