# Generated by Django 3.1.2 on 2020-10-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_remove_cpp_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='c',
            name='slug',
            field=models.SlugField(default='intro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cpp',
            name='slug',
            field=models.SlugField(default='intro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='java',
            name='slug',
            field=models.SlugField(default='intro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='javascript',
            name='slug',
            field=models.SlugField(default='intro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='php',
            name='slug',
            field=models.SlugField(default='intro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='python',
            name='slug',
            field=models.SlugField(default='intro'),
            preserve_default=False,
        ),
    ]
