# Generated by Django 3.1.2 on 2020-12-27 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_auto_20201017_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='python',
            name='next_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='tutorials.python'),
        ),
        migrations.AddField(
            model_name='python',
            name='previous_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='tutorials.python'),
        ),
    ]
