# Generated by Django 3.1.2 on 2020-12-28 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0007_python_course_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='c',
            name='course_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='c',
            name='next_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='tutorials.c'),
        ),
        migrations.AddField(
            model_name='c',
            name='previous_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='tutorials.c'),
        ),
        migrations.AddField(
            model_name='cpp',
            name='course_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cpp',
            name='next_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='tutorials.cpp'),
        ),
        migrations.AddField(
            model_name='cpp',
            name='previous_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='tutorials.cpp'),
        ),
        migrations.AddField(
            model_name='java',
            name='course_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='java',
            name='next_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='tutorials.java'),
        ),
        migrations.AddField(
            model_name='java',
            name='previous_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='tutorials.java'),
        ),
        migrations.AddField(
            model_name='javascript',
            name='course_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='javascript',
            name='next_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='tutorials.javascript'),
        ),
        migrations.AddField(
            model_name='javascript',
            name='previous_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='tutorials.javascript'),
        ),
        migrations.AddField(
            model_name='php',
            name='course_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='php',
            name='next_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='tutorials.php'),
        ),
        migrations.AddField(
            model_name='php',
            name='previous_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='tutorials.php'),
        ),
        migrations.AlterField(
            model_name='python',
            name='course_number',
            field=models.IntegerField(default=0),
        ),
    ]
